import type { BibleBook } from "@/types";

// Canonical Protestant 66-book order with accurate chapter counts.
// bookId is the standard 3-letter USFM code api.bible uses to address books.
export const BIBLE_BOOKS: BibleBook[] = [
  { name: "Genesis", testament: "old", chapterCount: 50, bookId: "GEN" },
  { name: "Exodus", testament: "old", chapterCount: 40, bookId: "EXO" },
  { name: "Leviticus", testament: "old", chapterCount: 27, bookId: "LEV" },
  { name: "Numbers", testament: "old", chapterCount: 36, bookId: "NUM" },
  { name: "Deuteronomy", testament: "old", chapterCount: 34, bookId: "DEU" },
  { name: "Joshua", testament: "old", chapterCount: 24, bookId: "JOS" },
  { name: "Judges", testament: "old", chapterCount: 21, bookId: "JDG" },
  { name: "Ruth", testament: "old", chapterCount: 4, bookId: "RUT" },
  { name: "1 Samuel", testament: "old", chapterCount: 31, bookId: "1SA" },
  { name: "2 Samuel", testament: "old", chapterCount: 24, bookId: "2SA" },
  { name: "1 Kings", testament: "old", chapterCount: 22, bookId: "1KI" },
  { name: "2 Kings", testament: "old", chapterCount: 25, bookId: "2KI" },
  { name: "1 Chronicles", testament: "old", chapterCount: 29, bookId: "1CH" },
  { name: "2 Chronicles", testament: "old", chapterCount: 36, bookId: "2CH" },
  { name: "Ezra", testament: "old", chapterCount: 10, bookId: "EZR" },
  { name: "Nehemiah", testament: "old", chapterCount: 13, bookId: "NEH" },
  { name: "Esther", testament: "old", chapterCount: 10, bookId: "EST" },
  { name: "Job", testament: "old", chapterCount: 42, bookId: "JOB" },
  { name: "Psalms", testament: "old", chapterCount: 150, bookId: "PSA" },
  { name: "Proverbs", testament: "old", chapterCount: 31, bookId: "PRO" },
  { name: "Ecclesiastes", testament: "old", chapterCount: 12, bookId: "ECC" },
  { name: "Song of Solomon", testament: "old", chapterCount: 8, bookId: "SNG" },
  { name: "Isaiah", testament: "old", chapterCount: 66, bookId: "ISA" },
  { name: "Jeremiah", testament: "old", chapterCount: 52, bookId: "JER" },
  { name: "Lamentations", testament: "old", chapterCount: 5, bookId: "LAM" },
  { name: "Ezekiel", testament: "old", chapterCount: 48, bookId: "EZK" },
  { name: "Daniel", testament: "old", chapterCount: 12, bookId: "DAN" },
  { name: "Hosea", testament: "old", chapterCount: 14, bookId: "HOS" },
  { name: "Joel", testament: "old", chapterCount: 3, bookId: "JOL" },
  { name: "Amos", testament: "old", chapterCount: 9, bookId: "AMO" },
  { name: "Obadiah", testament: "old", chapterCount: 1, bookId: "OBA" },
  { name: "Jonah", testament: "old", chapterCount: 4, bookId: "JON" },
  { name: "Micah", testament: "old", chapterCount: 7, bookId: "MIC" },
  { name: "Nahum", testament: "old", chapterCount: 3, bookId: "NAM" },
  { name: "Habakkuk", testament: "old", chapterCount: 3, bookId: "HAB" },
  { name: "Zephaniah", testament: "old", chapterCount: 3, bookId: "ZEP" },
  { name: "Haggai", testament: "old", chapterCount: 2, bookId: "HAG" },
  { name: "Zechariah", testament: "old", chapterCount: 14, bookId: "ZEC" },
  { name: "Malachi", testament: "old", chapterCount: 4, bookId: "MAL" },
  { name: "Matthew", testament: "new", chapterCount: 28, bookId: "MAT" },
  { name: "Mark", testament: "new", chapterCount: 16, bookId: "MRK" },
  { name: "Luke", testament: "new", chapterCount: 24, bookId: "LUK" },
  { name: "John", testament: "new", chapterCount: 21, bookId: "JHN" },
  { name: "Acts", testament: "new", chapterCount: 28, bookId: "ACT" },
  { name: "Romans", testament: "new", chapterCount: 16, bookId: "ROM" },
  { name: "1 Corinthians", testament: "new", chapterCount: 16, bookId: "1CO" },
  { name: "2 Corinthians", testament: "new", chapterCount: 13, bookId: "2CO" },
  { name: "Galatians", testament: "new", chapterCount: 6, bookId: "GAL" },
  { name: "Ephesians", testament: "new", chapterCount: 6, bookId: "EPH" },
  { name: "Philippians", testament: "new", chapterCount: 4, bookId: "PHP" },
  { name: "Colossians", testament: "new", chapterCount: 4, bookId: "COL" },
  { name: "1 Thessalonians", testament: "new", chapterCount: 5, bookId: "1TH" },
  { name: "2 Thessalonians", testament: "new", chapterCount: 3, bookId: "2TH" },
  { name: "1 Timothy", testament: "new", chapterCount: 6, bookId: "1TI" },
  { name: "2 Timothy", testament: "new", chapterCount: 4, bookId: "2TI" },
  { name: "Titus", testament: "new", chapterCount: 3, bookId: "TIT" },
  { name: "Philemon", testament: "new", chapterCount: 1, bookId: "PHM" },
  { name: "Hebrews", testament: "new", chapterCount: 13, bookId: "HEB" },
  { name: "James", testament: "new", chapterCount: 5, bookId: "JAS" },
  { name: "1 Peter", testament: "new", chapterCount: 5, bookId: "1PE" },
  { name: "2 Peter", testament: "new", chapterCount: 3, bookId: "2PE" },
  { name: "1 John", testament: "new", chapterCount: 5, bookId: "1JN" },
  { name: "2 John", testament: "new", chapterCount: 1, bookId: "2JN" },
  { name: "3 John", testament: "new", chapterCount: 1, bookId: "3JN" },
  { name: "Jude", testament: "new", chapterCount: 1, bookId: "JUD" },
  { name: "Revelation", testament: "new", chapterCount: 22, bookId: "REV" },
];

export function findBook(name: string): BibleBook | undefined {
  return BIBLE_BOOKS.find((book) => book.name === name);
}
