import type { ReactElement } from "react";
import {
  Sofa,
  Armchair,
  Tv,
  Table2,
  CookingPot,
  Refrigerator,
  Droplet,
  Bed,
  Archive,
  Lamp,
  DoorClosed,
  ShowerHead,
  Frame,
  Blinds,
  PencilRuler,
  Presentation,
  BookOpenText,
  Globe,
  Laptop,
  Target,
  StretchHorizontal,
  GaugeCircle,
  Layers,
  UtensilsCrossed,
  Container,
  Trash2,
  Newspaper,
  ActivitySquare,
  Syringe,
  ShoppingCart,
  Wallet,
  PillBottle,
  Podcast,
  Church,
  Music,
  Music2,
  Piano,
  Baby,
  Box,
  Luggage,
  Wine,
  GlassWater,
  Umbrella,
  Waves,
  Crown,
  Flag,
  LayoutGrid,
  Flame,
  MoveVertical,
  AppWindow,
  Bell,
  FlameKindling,
  Link2,
  Barrel,
  Package,
} from "lucide-react";

// Close-enough Lucide icon for a verse's own free-text location tag (lowercased) — shown
// alongside VerseVisualBadge.tsx's corner badge once a verse has been visualized. Covers
// common household/room-ish words as a nicety; a tag that matches none of them just falls
// back to a generic box icon rather than needing 1:1 coverage of everything someone might type.
const FURNITURE_ICONS: Record<string, typeof Package> = {
  sofa: Sofa,
  armchair: Armchair,
  "lounge chair": Armchair,
  "rocking chair": Armchair,
  chair: Armchair,
  chairs: Armchair,
  "tv stand": Tv,
  tv: Tv,
  "coffee table": Table2,
  table: Table2,
  "long table": Table2,
  "reading table": Table2,
  "tray table": Table2,
  "changing table": Table2,
  counter: Table2,
  "kitchen counter": Table2,
  stove: CookingPot,
  fridge: Refrigerator,
  sink: Droplet,
  bed: Bed,
  "hospital bed": Bed,
  dresser: Archive,
  shelf: Archive,
  nightstand: Lamp,
  chandelier: Lamp,
  lamp: Lamp,
  closet: DoorClosed,
  cell: DoorClosed,
  shower: ShowerHead,
  mirror: Frame,
  tapestry: Frame,
  "towel rack": Blinds,
  "coat rack": Blinds,
  "robe rack": Blinds,
  curtain: Blinds,
  desk: PencilRuler,
  "reception desk": PencilRuler,
  "front desk": PencilRuler,
  whiteboard: Presentation,
  bookshelf: BookOpenText,
  globe: Globe,
  computer: Laptop,
  "basketball hoop": Target,
  bleachers: StretchHorizontal,
  bench: StretchHorizontal,
  scoreboard: GaugeCircle,
  mat: Layers,
  rug: LayoutGrid,
  "lunch tray": UtensilsCrossed,
  "vending machine": Container,
  "trash can": Trash2,
  "magazine rack": Newspaper,
  "menu stand": Newspaper,
  stretcher: ActivitySquare,
  monitor: ActivitySquare,
  "iv stand": Syringe,
  cart: ShoppingCart,
  "cash register": Wallet,
  "pill bottles": PillBottle,
  pulpit: Podcast,
  altar: Church,
  organ: Music,
  piano: Piano,
  "music stand": Music2,
  crib: Baby,
  "toy bin": Box,
  "luggage cart": Luggage,
  minibar: Wine,
  bar: GlassWater,
  umbrella: Umbrella,
  pool: Waves,
  throne: Crown,
  banner: Flag,
  fireplace: Flame,
  "spiral staircase": MoveVertical,
  window: AppWindow,
  bell: Bell,
  torch: FlameKindling,
  chain: Link2,
  barrel: Barrel,
};

export function furnitureIcon(label: string, size: number): ReactElement {
  const Icon = FURNITURE_ICONS[label.toLowerCase()] ?? Package;
  return <Icon size={size} />;
}
